low_level: fix missing encoding line
Without this:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "argon2/__init__.py", line 5, in <module>
    from . import exceptions, low_level
  File "argon2/low_level.py", line 6
SyntaxError: Non-ASCII character '\xe2' in file argon2/low_level.py on line 7, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```